### ISSUE TITLE
Prepare readme for release

### ISSUE THREAD

**Issue by badboy** [acmiyaguchi/jsonschema-transpiler#46]
Related: #35 

IMO we should have the following information in the readme:

1. What is it, where is it used
2. installation
3. Usage examples
4. How to contribute
5. License & CoC

The new docs from #44 could move into its own docs (`docs/development.md`) to not blow up the readme too much.

What do you think?

**Comment by acmiyaguchi** [comment]
This organization sounds great, I think this would make the readme easier to digest. Having a separate docs folder will be nice for dropping in some of the longer-form information about each of the individual schemas, too.
